package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"time"

	"high-performance-news-website/internal/models"
	"high-performance-news-website/internal/services"
)

// Simple cache implementation for demo
type DemoCacheService struct{}

func (d *DemoCacheService) Get(ctx context.Context, key string) ([]byte, error) {
	return nil, nil
}

func (d *DemoCacheService) Set(ctx context.Context, key string, value []byte, ttl time.Duration) error {
	return nil
}

func (d *DemoCacheService) Delete(ctx context.Context, key string) error {
	return nil
}

func (d *DemoCacheService) DeletePattern(ctx context.Context, pattern string) error {
	return nil
}

func (d *DemoCacheService) Exists(ctx context.Context, key string) (bool, error) {
	return false, nil
}

func (d *DemoCacheService) Close() error {
	return nil
}

func (d *DemoCacheService) Health(ctx context.Context) error {
	return nil
}

func main() {
	// Create temporary directories for demo
	tempDir, err := os.MkdirTemp("", "static_generator_demo")
	if err != nil {
		log.Fatal("Failed to create temp directory:", err)
	}
	defer os.RemoveAll(tempDir)

	templatesDir := filepath.Join(tempDir, "templates")
	outputDir := filepath.Join(tempDir, "output")

	// Create template directory
	if err := os.MkdirAll(templatesDir, 0755); err != nil {
		log.Fatal("Failed to create templates directory:", err)
	}

	// Create basic templates
	createDemoTemplates(templatesDir)

	// Create static generator
	config := services.StaticGeneratorConfig{
		OutputPath:   outputDir,
		TemplatesDir: templatesDir,
		BaseURL:      "https://demo.example.com",
	}

	cacheService := &DemoCacheService{}
	sg, err := services.NewStaticGenerator(config, cacheService, nil, nil, nil)
	if err != nil {
		log.Fatal("Failed to create static generator:", err)
	}

	ctx := context.Background()

	// Create demo article
	publishedAt := time.Now()
	article := &models.Article{
		ID:           1,
		Title:        "Demo Article: Static Generation in Action",
		Slug:         "demo-article-static-generation",
		Content:      "<p>This is a demonstration of our static HTML generation system.</p><p>The system creates optimized static files for maximum performance.</p>",
		Excerpt:      "A demonstration of static HTML generation for high-performance news delivery.",
		CategoryID:   1,
		PublishedAt:  &publishedAt,
		UpdatedAt:    time.Now(),
		LanguageCode: "en",
		SEOData: models.SEOData{
			MetaTitle:       "Demo Article - Static Generation",
			MetaDescription: "Learn how our static generation system works",
			Keywords:        []string{"demo", "static", "generation", "performance"},
			SchemaType:      "NewsArticle",
		},
	}

	// Generate article page
	fmt.Println("Generating article page...")
	if err := sg.GenerateArticlePage(ctx, article); err != nil {
		log.Fatal("Failed to generate article page:", err)
	}

	// Check if file was created
	articleFile := filepath.Join(outputDir, "articles", "demo-article-static-generation", "index.html")
	if _, err := os.Stat(articleFile); err == nil {
		fmt.Printf("✅ Article page generated successfully: %s\n", articleFile)
		
		// Read and display first few lines
		content, err := os.ReadFile(articleFile)
		if err == nil {
			fmt.Println("\n📄 Generated HTML preview:")
			fmt.Println("---")
			lines := string(content)
			if len(lines) > 500 {
				lines = lines[:500] + "..."
			}
			fmt.Println(lines)
			fmt.Println("---")
		}
	} else {
		fmt.Printf("❌ Article page not found: %s\n", articleFile)
	}

	fmt.Printf("\n🎉 Static generation demo completed!\n")
	fmt.Printf("📁 Output directory: %s\n", outputDir)
	fmt.Printf("🌐 Base URL: %s\n", config.BaseURL)
}

func createDemoTemplates(templatesDir string) {
	// Create article template
	articleTemplate := `<!DOCTYPE html>
<html lang="{{.Language}}" dir="{{.Direction}}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{.Title}}</title>
    <meta name="description" content="{{.Description}}">
    <link rel="canonical" href="{{.CanonicalURL}}">
    <style>
        body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
        .article-header { border-bottom: 2px solid #eee; padding-bottom: 20px; margin-bottom: 20px; }
        .article-meta { color: #666; font-size: 14px; margin: 10px 0; }
        .article-body { line-height: 1.6; }
        .demo-badge { background: #007cba; color: white; padding: 5px 10px; border-radius: 3px; font-size: 12px; }
    </style>
</head>
<body>
    <div class="demo-badge">🚀 Generated by Static Generator</div>
    <article>
        <header class="article-header">
            <h1>{{.Article.Title}}</h1>
            <div class="article-meta">
                <time datetime="{{.Article.PublishedAt}}">Published: {{.Article.PublishedAt}}</time>
                <br>
                <span>Language: {{.Article.LanguageCode}}</span>
                <br>
                <span>Slug: {{.Article.Slug}}</span>
            </div>
            {{if .Article.Excerpt}}
            <div class="article-excerpt">
                <strong>Excerpt:</strong> {{.Article.Excerpt}}
            </div>
            {{end}}
        </header>
        
        <div class="article-body">
            {{.Article.Content | safeHTML}}
        </div>
    </article>
    
    <footer style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; color: #666; font-size: 14px;">
        <p>Generated by High Performance News Website Static Generator</p>
        <p>Base URL: {{.BaseURL}}</p>
        <p>Canonical URL: {{.CanonicalURL}}</p>
    </footer>
</body>
</html>`

	if err := os.WriteFile(filepath.Join(templatesDir, "article.html"), []byte(articleTemplate), 0644); err != nil {
		log.Fatal("Failed to create article template:", err)
	}

	fmt.Println("✅ Demo templates created")
}